// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbhkhamT005GfKrD-e9OQoxuswf4jUepQ',
    appId: '1:543818854564:web:e3aa261e52d44f03ce7631',
    messagingSenderId: '543818854564',
    projectId: 'graduation-project-61d32',
    authDomain: 'graduation-project-61d32.firebaseapp.com',
    storageBucket: 'graduation-project-61d32.appspot.com',
    measurementId: 'G-CVJ18Q5MTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_6nyvzTTC50HyJjcnsaBcdfojjcxjHeM',
    appId: '1:543818854564:android:a13a2439eb170e9cce7631',
    messagingSenderId: '543818854564',
    projectId: 'graduation-project-61d32',
    storageBucket: 'graduation-project-61d32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOkseQEFZsJtA95Y5FvnrHfahYoOruG9Q',
    appId: '1:543818854564:ios:8c23939e2e05ffd7ce7631',
    messagingSenderId: '543818854564',
    projectId: 'graduation-project-61d32',
    storageBucket: 'graduation-project-61d32.appspot.com',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOkseQEFZsJtA95Y5FvnrHfahYoOruG9Q',
    appId: '1:543818854564:ios:8c23939e2e05ffd7ce7631',
    messagingSenderId: '543818854564',
    projectId: 'graduation-project-61d32',
    storageBucket: 'graduation-project-61d32.appspot.com',
    iosBundleId: 'com.example.graduationProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbhkhamT005GfKrD-e9OQoxuswf4jUepQ',
    appId: '1:543818854564:web:3295b234ef1333d2ce7631',
    messagingSenderId: '543818854564',
    projectId: 'graduation-project-61d32',
    authDomain: 'graduation-project-61d32.firebaseapp.com',
    storageBucket: 'graduation-project-61d32.appspot.com',
    measurementId: 'G-875KP61SEM',
  );
}
